# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

dockers:
- image_templates:
  - "ghcr.io/ajfriesen/fitlib:{{ .Version }}-amd64"
  - "ghcr.io/ajfriesen/fitlib:latest-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/ajfriesen/fitlib:{{ .Version }}-arm64v8"
  - "ghcr.io/ajfriesen/fitlib:latest-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: "ghcr.io/ajfriesen/fitlib:{{ .Version }}"
  image_templates:
  - "ghcr.io/ajfriesen/fitlib:{{ .Version }}-amd64"
  - "ghcr.io/ajfriesen/fitlib:latest-amd64"
  - "ghcr.io/ajfriesen/fitlib:{{ .Version }}-arm64v8"
  - "ghcr.io/ajfriesen/fitlib:latest-arm64v8"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

