include: package:lint/analysis_options.yaml

linter:
  rules:
    - parameter_assignments

analyzer:
#  plugins:
#    - dart_code_metrics
#  dart_code_metrics:
#    anti-patterns:
#      - long-method
#      - long-parameter-list

  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error

