// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Exercise struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

type WorkoutLog struct {
	ID          int64
	ExerciseID  int64
	Timestamp   string
	Reps        sql.NullInt64
	TimeSeconds sql.NullInt64
}
