// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Exercise struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

type ExerciseTracking struct {
	ID         interface{}
	ExerciseID int64
	Date       sql.NullString
	Timestamp  sql.NullString
	Reps       sql.NullInt64
	Notes      sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}
