// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const getAllExercises = `-- name: GetAllExercises :many
SELECT id, name, description, created_at, updated_at FROM exercises
`

func (q *Queries) GetAllExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getAllExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackedExercises = `-- name: GetTrackedExercises :one
SELECT et.id, et.exercise_id, et.date, et.timestamp, et.reps, et.notes, et.created_at, et.updated_at, e.name AS exercise_name
FROM exercise_tracking et
JOIN exercises e ON et.exercise_id = e.id
`

type GetTrackedExercisesRow struct {
	ID           interface{}
	ExerciseID   int64
	Date         sql.NullString
	Timestamp    sql.NullString
	Reps         sql.NullInt64
	Notes        sql.NullString
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
	ExerciseName string
}

func (q *Queries) GetTrackedExercises(ctx context.Context) (GetTrackedExercisesRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackedExercises)
	var i GetTrackedExercisesRow
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.Date,
		&i.Timestamp,
		&i.Reps,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExerciseName,
	)
	return i, err
}

const insertExercise = `-- name: InsertExercise :one
INSERT INTO exercises
(name, description, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertExerciseParams struct {
	Name        string
	Description sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) InsertExercise(ctx context.Context, arg InsertExerciseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertExercise,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTrackedExercise = `-- name: InsertTrackedExercise :one
INSERT INTO exercise_tracking
(exercise_id, reps, notes)
VALUES (?, ?, ?)
RETURNING id, exercise_id, date, timestamp, reps, notes, created_at, updated_at
`

type InsertTrackedExerciseParams struct {
	ExerciseID int64
	Reps       sql.NullInt64
	Notes      sql.NullString
}

func (q *Queries) InsertTrackedExercise(ctx context.Context, arg InsertTrackedExerciseParams) (ExerciseTracking, error) {
	row := q.db.QueryRowContext(ctx, insertTrackedExercise, arg.ExerciseID, arg.Reps, arg.Notes)
	var i ExerciseTracking
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.Date,
		&i.Timestamp,
		&i.Reps,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
