name: Build and push docker image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract git tag
        id: extract_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
          echo "::set-output name=GIT_TAG::$TAG"

      - name: Check for live tag
        id: check_live
        run: |
          if [[ "${{ steps.extract_tag.outputs.GIT_TAG }}" == "live" ]]; then
            echo "::set-output name=LIVE_TAG::true"
          else
            echo "::set-output name=LIVE_TAG::false"
          fi


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/ajfriesen/fitlib:latest
            ghcr.io/ajfriesen/fitlib:${{ steps.extract_tag.outputs.GIT_TAG }}
            ${{ steps.check_live.outputs.LIVE_TAG == 'true' && 'ghcr.io/ajfriesen/fitlib:live' || '' }}


